config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'home#index'
  get 'my-guesthouse', to: 'guesthouses#my_guesthouse'
  get 'guesthouses_by_city/:city', to: 'guesthouses#by_city', as: 'guesthouses_by_city'

  resources :guesthouses, only: [:new, :create, :show, :edit, :update] do
    post :activate, on: :member
    post :inactivate, on: :member
    get 'search', on: :collection
    get 'bookings', on: :member
    get 'active_stays', on: :member
    get 'reviews', on: :member
    get 'all_reviews', on: :member
    resources :rooms, only: [:new, :create]
  end

  resources :rooms, only: [:show, :edit, :update] do
    post :set_available, on: :member
    post :set_unavailable, on: :member
    resources :custom_prices, only: [:index, :new, :create]
    resources :bookings, only: [:new, :create] do
      post 'check_availability', on: :collection
    end
  end

  resources :custom_prices, only: [:edit, :update]
  get 'confirm_booking', to: 'bookings#confirm_booking'
  get 'my-bookings', to: 'bookings#my_bookings'

  resources :bookings, only: [:show] do
    post :set_in_progress, on: :member
    post :set_finished, on: :member
    get 'payment', on: :member
    patch 'register_payment', on: :member
    delete 'host_cancel', on: :member
    delete 'guest_cancel', on: :member
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [] do
    get 'answer', on: :member
    patch 'register_answer', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :guesthouses, only: [:index, :show] do
        resources :rooms, only: [:index]
      end
      resources :rooms, only: [] do
        resources :bookings, only: [] do
          post 'check_availability', on: :collection
        end
      end
    end
  end

end

app/controllers/api/v1/guesthouses_controller.rb
class Api::V1::GuesthousesController < Api::V1::ApiController

  def index
    guesthouses = Guesthouse.active
    if params[:search].present?
      guesthouses = guesthouses.where("brand_name LIKE ?", "%#{params[:search]}%")
    end    
    render status: 200, json: guesthouses.as_json(only: [:id, :brand_name, :city])
  end

  def show
    guesthouse = Guesthouse.find(params[:id])
    if guesthouse.inactive?
      return render status: 422, json: { error: 'Pousada inativa no momento' }
    else
      average_score = guesthouse.average_score
      guesthouse_json = guesthouse.as_json(except: [:corporate_name, :registration_number, :created_at, :updated_at, :user_id, :status])      
      guesthouse_json["check_in"] = guesthouse["check_in"].to_time.strftime('%H:%M')
      guesthouse_json["check_out"] = guesthouse["check_out"].to_time.strftime('%H:%M')  
      guesthouse_json["average_score"] = average_score.nil? ? '' : average_score.round(1)
      return render status: 200, json: guesthouse_json
    end
  end

end

app/controllers/guesthouses_controller.rb
class GuesthousesController < ApplicationController
  before_action :authenticate_user!, only: [:my_guesthouse, :new, :create, :edit, :update, :activate, :inactivate, 
                                            :bookings, :active_stays, :reviews]  
  before_action :redirect_host_to_new, only: [:my_guesthouse, :show, :edit, :update, :activate, :inactivate, :search, 
                                              :by_city, :bookings, :active_stays, :reviews, :all_reviews] 
  before_action :allow_only_host, only: [:new, :create]
  before_action :check_guesthouse_presence, only: [:new, :create]
  before_action only: [:edit, :update, :activate, :inactivate] do
    @guesthouse = Guesthouse.find(params[:id])
    check_user(@guesthouse)
  end
  before_action :guesthouse_inactive, only: [:show, :all_reviews]

  def my_guesthouse
    @guesthouse = current_user.guesthouse
  end

  def new
    @guesthouse = Guesthouse.new
  end

  def create
    @guesthouse = Guesthouse.new(guesthouse_params)
    @guesthouse.user = current_user
    if @guesthouse.save
      redirect_to @guesthouse, notice: 'Pousada cadastrada com sucesso.'
    else
      flash.now[:notice] = 'Pousada não cadastrada.'
      render 'new'
    end
  end

  def show
    if @guesthouse.user == current_user
      @rooms = @guesthouse.rooms.order(:name)
    else
      @rooms = @guesthouse.rooms.available.order(:name)
    end
    @last_reviews = @guesthouse.reviews.last(3)
  end

  def edit; end

  def update
    if @guesthouse.update(guesthouse_params)
      redirect_to @guesthouse, notice: 'Pousada atualizada com sucesso.'
    else
      flash.now[:notice] = 'Pousada não atualizada.'
      render 'edit'
    end
  end

  def activate
    @guesthouse.active!
    redirect_to guesthouse_path(@guesthouse.id), notice: 'Pousada ativada com sucesso.'
  end

  def inactivate
    @guesthouse.inactive!
    redirect_to guesthouse_path(@guesthouse.id), notice: 'Pousada desativada com sucesso.'
  end

  def search
    @query = params["query"]
    @guesthouses = Guesthouse.search(@query)
  end

  def by_city
    @city = params[:city]
    @guesthouses_by_city = Guesthouse.where(city: @city).active.order(:brand_name)
  end

  def bookings
    @guesthouse = current_user.guesthouse
    @bookings = @guesthouse.bookings.pending.order(check_in_date: :asc)
  end
  
  def active_stays
    @guesthouse = current_user.guesthouse
    @in_progress_bookings = @guesthouse.bookings.in_progress.order(check_in_date: :asc)
  end

  def reviews
    @guesthouse = current_user.guesthouse
    @reviews = @guesthouse.reviews
  end

  def all_reviews
    @all_reviews = @guesthouse.reviews
  end

  private

  def guesthouse_params
    params.require(:guesthouse).permit(:corporate_name, :brand_name, :registration_number, :phone_number, :email, :address, :neighborhood, 
                                        :state, :city, :postal_code, :description, :payment_method, :pet_agreement, :usage_policy, 
                                        :check_in, :check_out)
  end

  def check_guesthouse_presence
    if current_user.guesthouse.present?
      redirect_to my_guesthouse_path, alert: 'Só é possível ter uma pousada cadastrada por usuário!'
    end
  end

end

app/views/guesthouses/_form.html.erb
<div>
  <%= render partial: 'shared/error_messages', locals: { object: @guesthouse } %>
</div>

<%= form_with(model: @guesthouse) do |f| %>
<div class="row">
  <div class="field col-md-4">
    <%= f.label :corporate_name, class: "form-label" %>
    <%= f.text_field :corporate_name, class: "form-control" %>
  </div>
  <div class="field col-md-4">
    <%= f.label :brand_name, class: "form-label" %>
    <%= f.text_field :brand_name, class: "form-control" %>
  </div>
  <div class="field col-md-4">
    <%= f.label :registration_number, class: "form-label" %>
    <%= f.number_field :registration_number, class: "form-control" %>
  </div>
</div>

<div class="row">
  <div class="field col-md-4">
    <%= f.label :phone_number, class: "form-label" %>
    <%= f.number_field :phone_number, class: "form-control" %>
  </div>
  <div class="field col-md-4">
    <%= f.label :email, class: "form-label" %>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="field col-md-4">
    <%= f.label :address, class: "form-label" %>
    <%= f.text_field :address, class: "form-control" %>
  </div>
</div>

<div class="row">
  <div class="field col-md-4">
    <%= f.label :neighborhood, class: "form-label" %>
    <%= f.text_field :neighborhood, class: "form-control" %>
  </div>
  <div class="field col-md-4">
    <%= f.label :state, class: "form-label" %>
    <%= f.text_field :state, class: "form-control" %>
  </div>
  <div class="field col-md-4">
    <%= f.label :city, class: "form-label" %>
    <%= f.text_field :city, class: "form-control" %>
  </div>
</div>

<div class="row">
  <div class="field col-md-4">
    <%= f.label :postal_code, class: "form-label" %>
    <%= f.number_field :postal_code, class: "form-control" %>
  </div>
  <div class="field col-md-4">
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="field col-md-4">
    <%= f.label :payment_method, class: "form-label" %>
    <%= f.text_field :payment_method, class: "form-control" %>
  </div>
</div>

<div class="row">
  <div class="field col-md-4">
    <%= f.label :pet_agreement, class: "form-label" %>
    <%= f.text_field :pet_agreement, class: "form-control" %>
  </div>
  <div class="field col-md-4">
    <%= f.label :usage_policy, class: "form-label" %>
    <%= f.text_area :usage_policy, class: "form-control" %>
  </div>
  <div class="field col-md-2">
    <%= f.label :check_in, class: "form-label" %>
    <%= f.time_field :check_in, class: "form-control" %>
  </div>
  <div class="field col-md-2">
    <%= f.label :check_out, class: "form-label" %>
    <%= f.time_field :check_out, class: "form-control" %>
  </div>
</div>

<div>
  <%= f.submit 'Salvar', class: "btn btn-primary" %>
</div>
<% end %>
<br>
<div>
  <%= link_to 'Voltar', root_path %>
</div>

app/views/guesthouses/active_stays.html.erb
<section>
  <h2>Estadias Ativas</h2>
  <table style="border-collapse: collapse; width: 100%;">
    <thead>
      <tr>
        <th style="text-align: center; padding: 5px;">Código da Hospedagem</th>
        <th style="text-align: center; padding: 5px;">Quarto</th>
        <th style="text-align: center; padding: 5px;">Data de entrada</th>
        <th style="text-align: center; padding: 5px;">Data de saída</th>
        <th style="text-align: center; padding: 5px;">Quantidade de hóspedes</th>
      </tr>
    </thead>
    <tbody>
      <% @in_progress_bookings.each do |ip_booking| %>
        <tr>
          <td style="text-align: center; padding: 5px;"><%= link_to ip_booking.code, booking_path(ip_booking.id) %></td>
          <td style="text-align: center; padding: 5px;"><%= ip_booking.room.name %></td>
          <td style="text-align: center; padding: 5px;"><%= l(ip_booking.check_in_date) %></td>
          <td style="text-align: center; padding: 5px;"><%= l(ip_booking.check_out_date) %></td>
          <td style="text-align: center; padding: 5px;"><%= ip_booking.guests_number %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if @in_progress_bookings.empty? %>
    <p>Você não tem estadias ativas no momento.</p>
  <% end %>
</section> 

app/views/guesthouses/all_reviews.html.erb
<section>
  <h2>Avaliações da <%= @guesthouse.brand_name %></h2>
  <% @all_reviews.each do |review| %>
    <div>
      <p><strong><%= review.user.name %></strong> | 
      <strong>Nota: </strong><%= number_with_precision(review.score, separator: ',') %> | 
      <strong>Avaliação: </strong><%= review.review_text %></p>
    </div>
  <% end %>
</section>

app/views/guesthouses/bookings.html.erb
<section>
  <h2>Reservas</h2>
  <table style="border-collapse: collapse; width: 100%;">
    <thead>
      <tr>
        <th style="text-align: center; padding: 5px;">Código da Reserva</th>
        <th style="text-align: center; padding: 5px;">Quarto</th>
        <th style="text-align: center; padding: 5px;">Data de entrada</th>
        <th style="text-align: center; padding: 5px;">Data de saída</th>
        <th style="text-align: center; padding: 5px;">Quantidade de hóspedes</th>
      </tr>
    </thead>
    <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <td style="text-align: center; padding: 5px;"><%= link_to booking.code, booking_path(booking.id) %></td>
          <td style="text-align: center; padding: 5px;"><%= booking.room.name %></td>
          <td style="text-align: center; padding: 5px;"><%= l(booking.check_in_date) %></td>
          <td style="text-align: center; padding: 5px;"><%= l(booking.check_out_date) %></td>
          <td style="text-align: center; padding: 5px;"><%= booking.guests_number %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if @bookings.empty? %>
    <p>Você não tem reservas no momento.</p>
  <% end %>
</section> 

app/views/guesthouses/by_city.html.erb
<h2>Pousadas em <%= @city %>: </h2>
<% @guesthouses_by_city.each do |guesthouse_by_city| %>
  <ul>
    <li><%= link_to guesthouse_by_city.brand_name, guesthouse_by_city %></li>
  </ul>
<% end %>

app/views/guesthouses/edit.html.erb
<h2>Editar Pousada</h2>

<%= render 'form' %>

app/views/guesthouses/my_guesthouse.html.erb
<section>
  <div>
    <h2><%= link_to @guesthouse.brand_name, @guesthouse %></h2>
    <p><%= @guesthouse.city %></p>
  </div>
</section>

app/views/guesthouses/new.html.erb
<h2>Cadastrar Pousada</h2>

<%= render 'form' %>

app/views/guesthouses/reviews.html.erb
<h2>Avaliações</h2>
<section>
  <div style="width: 80%; margin: 0 auto;">
    <table style="border-collapse: collapse; width: 100%;">
      <thead>
        <tr>
          <th style="text-align: center; padding: 5px;">Código da Hospedagem</th>
          <th style="text-align: center; padding: 5px;">Avaliador</th>
          <th style="text-align: center; padding: 5px;">Nota</th>
          <th style="text-align: center; padding: 5px;">Avaliação</th>
        </tr>
      </thead>
      <tbody>
        <% @reviews.each do |review| %>
          <tr>
            <td style="text-align: center; padding: 5px;"><%= link_to review.booking.code, booking_path(review.booking.id) %></td>
            <td style="text-align: center; padding: 5px;"><%= review.booking.user.name %></td>
            <td style="text-align: center; padding: 5px;"><%= number_with_precision(review.score, separator: ',') %></td>
            <td style="text-align: center; padding: 5px;"><%= review.review_text %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <% if @reviews.empty? %>
    <p>Você não tem avaliações no momento.</p>
  <% end %>
</section>

app/views/guesthouses/search.html.erb
<h2>Resultados da Busca por: <%= @query %></h2>
<% if @guesthouses.present? %>
  <p><%= @guesthouses.count %> <%= Guesthouse.model_name.human(count: @guesthouses.count).downcase %> <%= t(:found, count: @guesthouses.count) %></p>
  <% @guesthouses.each do |guesthouse| %>
    <ul>
      <li><%= link_to guesthouse.brand_name, guesthouse %></li>
    </ul>
  <% end %>
<% else %>
  <p>Nenhum resultado encontrado.</p>
<% end%>

app/views/guesthouses/show.html.erb
<section>
  <% if current_user == @guesthouse.user %>
    <div>
      <p><strong>Status: </strong><%= I18n.t(@guesthouse.status) %></p>
      <% if @guesthouse.inactive? %>
        <%= button_to 'Ativar Pousada', activate_guesthouse_path(@guesthouse), class: 'btn btn-primary' %>
      <% else %>
        <%= button_to 'Desativar Pousada', inactivate_guesthouse_path(@guesthouse), class: 'btn btn-primary' %>
      <% end %>
      <%= link_to 'Editar', edit_guesthouse_path(@guesthouse) %> | 
      <%= link_to 'Cadastrar novo Quarto', new_guesthouse_room_path(@guesthouse) %> |
      <%= link_to 'Voltar', root_path %>
    </div>
  <% else %>
    <div>
      <%= link_to 'Voltar', root_path %>
    </div>
  <% end %>
</section>

<section>
  <h2><%= @guesthouse.brand_name %></h2>
  <p><strong>Nota Média: </strong><%= number_with_precision(@guesthouse.average_score, separator: ',')  %></p>
  <% if current_user == @guesthouse.user %>
    <p><strong>Razão Social: </strong><%= @guesthouse.corporate_name %></p>
    <p><strong>CNPJ: </strong><%= @guesthouse.registration_number %></p>
  <% end %>
  <p><strong>Telefone para contato: </strong><%= @guesthouse.phone_number %></p>
  <p><strong>E-mail para contato: </strong><%= @guesthouse.email %></p>
  <p><strong>Endereço Completo: </strong><%= @guesthouse.full_address %></p>
  <p><strong>Descrição: </strong><%= @guesthouse.description %></p>
  <p><strong>Métodos de Pagamento: </strong><%= @guesthouse.payment_method %></p>
  <p><strong>Aceita animais de estimação? </strong><%= @guesthouse.pet_agreement %></p>
  <p><strong>Políticas de Uso: </strong><%= @guesthouse.usage_policy %></p>
  <p><strong>Check-in: </strong><%= l(@guesthouse.check_in, format: "%H:%M") %></p>
  <p><strong>Check-out: </strong><%= l(@guesthouse.check_out, format: "%H:%M") %></p>
</section>
<hr>
<section>
  <h2>Quartos da Pousada</h2>
  <div class="room-container">
    <% @rooms.each do |room| %>
      <div class="l-room">
        <h3><%= link_to room.name, room %></h3>
        <p><strong>Descrição: </strong><%= room.description %></p>
        <p><strong>Valor da diária: </strong><%= number_to_currency(room.current_daily_price(Date.today), unit: "R$", separator: ",", delimiter: ".") %></p>
      </div>
    <% end %>
  </div>

  <% if @rooms.empty? %>
    <p>Não existem quartos cadastrados.</p>
  <% end %>
</section>
<hr>
<section>
  <h2>Avaliações da Pousada</h2>
  <% @last_reviews.each do |review| %>
    <div>
      <p><strong><%= review.user.name %></strong> | 
      <strong>Nota: </strong><%= number_with_precision(review.score, separator: ',') %> | 
      <strong>Avaliação: </strong><%= review.review_text %></p>
    </div>
  <% end %>

  <% if @last_reviews.empty? %>
    <p>Não existem avaliações cadastradas.</p>
  <% else %>
  <p><%= link_to 'Ver mais avaliações', all_reviews_guesthouse_path(@guesthouse) %></p>
  <% end %>
</section>