config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'home#index'
  get 'my-guesthouse', to: 'guesthouses#my_guesthouse'
  get 'guesthouses_by_city/:city', to: 'guesthouses#by_city', as: 'guesthouses_by_city'

  resources :guesthouses, only: [:new, :create, :show, :edit, :update] do
    post :activate, on: :member
    post :inactivate, on: :member
    get 'search', on: :collection
    get 'bookings', on: :member
    get 'active_stays', on: :member
    get 'reviews', on: :member
    get 'all_reviews', on: :member
    resources :rooms, only: [:new, :create]
  end

  resources :rooms, only: [:show, :edit, :update] do
    post :set_available, on: :member
    post :set_unavailable, on: :member
    resources :custom_prices, only: [:index, :new, :create]
    resources :bookings, only: [:new, :create] do
      post 'check_availability', on: :collection
    end
  end

  resources :custom_prices, only: [:edit, :update]
  get 'confirm_booking', to: 'bookings#confirm_booking'
  get 'my-bookings', to: 'bookings#my_bookings'

  resources :bookings, only: [:show] do
    post :set_in_progress, on: :member
    post :set_finished, on: :member
    get 'payment', on: :member
    patch 'register_payment', on: :member
    delete 'host_cancel', on: :member
    delete 'guest_cancel', on: :member
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [] do
    get 'answer', on: :member
    patch 'register_answer', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :guesthouses, only: [:index, :show] do
        resources :rooms, only: [:index]
      end
      resources :rooms, only: [] do
        resources :bookings, only: [] do
          post 'check_availability', on: :collection
        end
      end
    end
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one :review
  has_one :guesthouse, through: :room
  enum status: {pending: 0, in_progress: 2, finished: 4, canceled: 6}
  
  validates :check_in_date, :check_out_date, :guests_number, presence: true
  validates :payment_amount, :payment_method, presence: true, if: :register_payment_action?
  validate :check_dates
  validate :check_guests_number
  attr_accessor :register_payment_context

  before_validation :generate_code, on: :create

  def allow_check_in
    if Date.today >= self.check_in_date
      self.in_progress!
      self.update(check_in_done: Time.current)
      return true
    else
      return false
    end
  end

  def calculate_total_price
    total_price = 0
    current_date = self.check_in_date
  
    while current_date < self.check_out_date
      daily_price = room.current_daily_price(current_date)  
      total_price += daily_price  
      current_date += 1.day
    end
    total_price
  end

  def calculate_payment_amount
    total_price = 0
    current_date = self.check_in_done.to_date

    while current_date < self.check_out_done.to_date
      daily_price = room.current_daily_price(current_date)  
      total_price += daily_price  
      current_date += 1.day
    end

    if self.check_out_done.strftime('%H:%M') > guesthouse.check_out.strftime('%H:%M')
      total_price += room.current_daily_price(self.check_out_done)
    end
    total_price
  end

  def host_cancel_booking
    if Date.today >= (self.check_in_date + 2)
      true
    else
      false
    end
  end

  def guest_cancel_booking
    if Date.today <= (self.check_in_date - 7)
      true
    else
      false
    end
  end

  private

  def check_dates
    if room.present? && room.bookings.where.not(id: self.id)
                          .where('(check_in_date <= ? AND check_out_date >= ?) OR (check_in_date <= ? AND check_out_date >= ?) OR 
                          (check_in_date >= ? AND check_out_date <= ?)',
                          self.check_out_date, self.check_in_date, self.check_in_date, self.check_out_date,
                          self.check_in_date, self.check_out_date).exists?
      errors.add(:base, 'O quarto não está disponível para o período selecionado.')
    end
    if self.check_in_date.present? && self.check_out_date.present?
      errors.add(:check_in_date, ' deve ser anterior à data de saída') if self.check_in_date > self.check_out_date
    end
  end

  def check_guests_number 
    if room.present? && self.guests_number && self.guests_number > room.max_guest
      errors.add(:guests_number, ' ultrapassa o permitido para o quarto.')
    end
  end

  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end

  def register_payment_action?
    register_payment_context.present?
  end

end

app/controllers/api/v1/bookings_controller.rb
class Api::V1::BookingsController < Api::V1::ApiController

  def check_availability
    room = Room.find(params[:room_id])
    booking_params = params.require(:booking).permit(:check_in_date, :check_out_date, :guests_number)
    booking = room.bookings.build(booking_params)
    if booking.valid?
      total_price = booking.calculate_total_price
      booking_json = booking.as_json(only: [:total_price])
      booking_json["total_price"] = total_price
      render status: 200, json: booking_json
    else
      render status: 412, json: { errors: booking.errors.full_messages }
    end
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: [:my_bookings, :confirm_booking, :create, :show, :set_in_progress, :set_finished,
                                            :payment, :register_payment, :host_cancel, :guest_cancel]
  before_action :redirect_host_to_new
  before_action only: [:set_in_progress, :set_finished, :payment, :register_payment, :host_cancel] do
    @booking = Booking.find(params[:id])
    @guesthouse = @booking.guesthouse
    check_user(@guesthouse)
  end
  before_action only: [:guest_cancel] do
    @booking = Booking.find(params[:id])
    check_user(@booking)
  end

  def my_bookings
    @my_bookings_pending = current_user.bookings.pending
    @my_bookings_finished = current_user.bookings.finished
  end

  def new
    @room = Room.find(params[:room_id])
    @booking = @room.bookings.build
  end

  def check_availability
    @room = Room.find(params[:room_id])
    @booking = @room.bookings.build(booking_params)

    if @booking.valid?
      @total_price = @booking.calculate_total_price
      session['booking_data'] = {room_id: @room.id, room_name: @room.name, checkin: @booking.check_in_date, 
                                  checkout: @booking.check_out_date, guests_number: @booking.guests_number, total_price: @total_price}
      render 'show_availability'
    else
      render 'new'
    end
  end

  def confirm_booking
    booking_data_session
    @room = Room.find(@room_id)
    @guesthouse = @room.guesthouse
  end

  def create
    booking_data_session
    @booking = Booking.new(room_id: @room_id, check_in_date: @checkin_date, check_out_date: @checkout_date, guests_number: @guests_number) 
    @booking.user = current_user
    if @booking.save
      session.delete('booking_data')
      redirect_to my_bookings_path, notice: 'Reserva realizada com sucesso.'
    else
      redirect_to room_path(@room_id), notice: 'Reserva não realizada.'
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @review = @booking.review
  end

  def set_in_progress
    if @booking.allow_check_in
      redirect_to booking_path(@booking), notice: 'Check-in realizado com sucesso.'
    else
      redirect_to booking_path(@booking), alert: 'Ainda não é possível realizar o check-in dessa reserva.'
    end
  end

  def set_finished
    @booking.finished!
    @booking.update(check_out_done: Time.current)
    redirect_to payment_booking_path(@booking)
  end

  def payment
    @payment_amount = @booking.calculate_payment_amount
    if @booking.check_out_done.strftime('%H:%M') > @booking.room.guesthouse.check_out.strftime('%H:%M')
      flash[:notice] = 'Check-out realizado com sucesso mas depois do horário previsto, portanto será cobrada mais uma diária.'
    else
      flash[:notice] = 'Check-out realizado com sucesso dentro do horário previsto.'
    end
  end

  def register_payment
    @booking.register_payment_context = true
    payment_params = params.require(:booking).permit(:payment_amount, :payment_method)  
    if @booking.update(payment_params)
      redirect_to my_guesthouse_path, notice: 'Pagamento registrado com sucesso.'
    else
      flash.now[:notice] = 'Pagamento não registrado.'
      render 'payment'
    end
  end

  def host_cancel
    if @booking.host_cancel_booking
      @booking.destroy
      redirect_to bookings_guesthouse_path(@guesthouse), notice: 'Reserva cancelada com sucesso.'
    else
      redirect_to booking_path(@booking), alert: 'Só é possível cancelar a reserva após 2 dias da data prevista para o check-in.'
    end
  end

  def guest_cancel
    if @booking.guest_cancel_booking
      @booking.destroy
      redirect_to my_bookings_path, notice: 'Reserva cancelada com sucesso.'
    else
      redirect_to booking_path(@booking), alert: 'Só é possível cancelar a reserva até 7 dias antes da data prevista para o check-in.'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:check_in_date, :check_out_date, :guests_number)
  end

  def booking_data_session
    booking_data_session = session.fetch('booking_data', {})
    @room_id = booking_data_session['room_id']
    @room_name = booking_data_session['room_name']
    @checkin_date = Date.parse(booking_data_session['checkin'])
    @checkout_date = Date.parse(booking_data_session['checkout'])
    @guests_number = booking_data_session['guests_number']
    @total_price = booking_data_session['total_price']
  end

end

app/views/bookings/_bookings_table.html.erb
<table style="border-collapse: collapse; width: 100%;">
  <thead>
    <tr>
      <th style="text-align: center; padding: 5px;">Código da Reserva</th>
      <th style="text-align: center; padding: 5px;">Pousada</th>
      <th style="text-align: center; padding: 5px;">Quarto</th>
      <th style="text-align: center; padding: 5px;">Data de entrada</th>
      <th style="text-align: center; padding: 5px;">Data de saída</th>
      <th style="text-align: center; padding: 5px;">Quantidade de hóspedes</th>
    </tr>
  </thead>
  <tbody>
    <% bookings.each do |booking| %>
      <tr>
        <td style="text-align: center; padding: 5px;"><%= link_to booking.code, booking_path(booking.id) %></td>
        <td style="text-align: center; padding: 5px;"><%= booking.guesthouse.brand_name %></td>
        <td style="text-align: center; padding: 5px;"><%= booking.room.name %></td>
        <td style="text-align: center; padding: 5px;"><%= l(booking.check_in_date) %></td>
        <td style="text-align: center; padding: 5px;"><%= l(booking.check_out_date) %></td>
        <td style="text-align: center; padding: 5px;"><%= booking.guests_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/confirm_booking.html.erb
<h2>Resumo da Reserva</h2>
<p><strong>Quarto escolhido: </strong><%= @room_name %></p>
<p><strong>Data de entrada: </strong><%= l(@checkin_date) %> - 
    <strong>Horário de checkin: </strong><%= l(@guesthouse.check_in, format: "%H:%M") %></p>
<p><strong>Data de saída: </strong><%= l(@checkout_date) %> - 
    <strong>Horário de checkout: </strong><%= l(@guesthouse.check_out, format: "%H:%M")%></p>
<p><strong>Valor total das diárias: </strong><%= number_to_currency(@total_price, unit: "R$", separator: ",", delimiter: ".") %></p>
<p><strong>Meios de pagamento aceitos pela pousada: </strong><%= @guesthouse.payment_method %></p>
<p><strong>Atenção: </strong>Após a reserva ser confirmada, ela pode ser cancelada até 7 dias antes da data agendada para o check-in.</p>
<%= button_to 'Confirmar Reserva', room_bookings_path(room_id: @room_id), class: 'btn btn-primary' %>

app/views/bookings/my_bookings.html.erb
<h2>Minhas Reservas</h2>
<section>
  <h3>Reservas Pendentes:</h3>
  <%= render partial: 'bookings_table', locals: { bookings: @my_bookings_pending } %>

  <% if @my_bookings_pending.empty? %>
    <p>Você não tem reservas pendentes no momento.</p>
  <% end %>
</section> 

<section>
  <h3>Reservas Finalizadas</h3>
  <%= render partial: 'bookings_table', locals: { bookings: @my_bookings_finished } %>

  <% if @my_bookings_finished.empty? %>
    <p>Você não tem reservas finalizadas no momento.</p>
  <% end %>
</section>

app/views/bookings/new.html.erb
<section>
  <h2><%= @room.name %></h2>
  <p><strong>Descrição: </strong><%= @room.description %></p>
  <p><strong>Área (m²): </strong><%= @room.area %></p>
  <p><strong>Quantidade max. de hóspedes: </strong><%= @room.max_guest %></p>
  <p><strong>Valor da diária: </strong><%= number_to_currency(@room.current_daily_price(Date.today), unit: "R$", separator: ",", delimiter: ".") %></p>

  <p><strong>O que esse quarto oferece:</strong></p>
  <% @room.attributes.each do |attribute, value| %>
    <% if value == true %>
      <ul>
        <li><%= Room.human_attribute_name(attribute) %></li>
      </ul>
    <% end %>
  <% end %>
</section>

<section>
  <div>
    <%= render partial: 'shared/error_messages', locals: { object: @booking } %>
  </div>

  <h2>Consulte a Disponibilidade do <%= @room.name %>:</h2>
  <%= form_with(model: [@room, @booking], url: check_availability_room_bookings_path(@room, @booking)) do |f| %>
    <div class="row">
      <div class="field col-md-4">
        <%= f.label :check_in_date, class: "form-label" %>
        <%= f.date_field :check_in_date, class: "form-control" %>
      </div>
      <div class="field col-md-4">
        <%= f.label :check_out_date, class: "form-label" %>
        <%= f.date_field :check_out_date, class: "form-control" %>
      </div>
      <div class="field col-md-4">
        <%= f.label :guests_number, class: "form-label" %>
        <%= f.number_field :guests_number, class: "form-control" %>
      </div>
    </div>
    <br>

    <div>
      <%= f.submit 'Consultar', class: "btn btn-primary" %>
    </div>
  <% end %>
</section>

app/views/bookings/payment.html.erb
<section>
<% if @booking.finished? %>
  <div>
    <h2>Pagamento da Hospedagem <%= @booking.code %></h2>
    <p><strong>Check-out realizado em: </strong><%= l(@booking.check_out_done, format: '%d/%m/%Y, às %H:%M horas') %></p>
    <p><strong>Período da hospedagem: </strong>
      <%= l(@booking.check_in_done, format: '%d/%m/%Y') %> a <%= l(@booking.check_out_done, format: '%d/%m/%Y') %></p>
    <p><strong>Valor total a pagar: </strong><%= number_to_currency(@payment_amount, unit: "R$", separator: ",", delimiter: ".") %></p>
  </div>

  <div>
    <%= render partial: 'shared/error_messages', locals: { object: @booking } %>
  </div>

  <div>
    <%= form_with(model: @booking, url: register_payment_booking_path(@booking), method: :patch) do |f| %>
      <div class="row">
        <div class="field col-md-4">
          <%=f.label :payment_amount, class: "form-label" %>
          <%=f.number_field :payment_amount, class: "form-control" %>
        </div>
        <div class="field col-md-4">
          <%=f.label :payment_method, class: "form-label" %>
          <%=f.text_field :payment_method, class: "form-control" %>
        </div>
      </div>
      <br>

      <div>
        <%=f.submit 'Registrar Pagamento', class: "btn btn-primary" %>
      </div>      
    <% end %>
  </div>

<% end %> 
</section>

app/views/bookings/show.html.erb
<section>
  <% if @booking.pending? %>
    <h2>Reserva <%= @booking.code %></h2>
    <% if current_user.guest? %>
      <p><strong>Pousada: </strong><%= @booking.guesthouse.brand_name %></p>
    <% end %>
    <p><strong>Quarto: </strong><%= @booking.room.name %></p>
    <p><strong>Data de entrada: </strong><%= l(@booking.check_in_date) %></p>
    <p><strong>Data de saída: </strong><%= l(@booking.check_out_date) %></p>
    <p><strong>Quantidade de hóspedes: </strong><%= @booking.guests_number %></p>
    <p><strong>Status: </strong><%= t(@booking.status) %></p>
    <br>
    <%= button_to 'Realizar Check-in', set_in_progress_booking_path(@booking), class: 'btn btn-primary' if current_user.guesthouse %>
    <br>
    <%= button_to 'Cancelar Reserva', host_cancel_booking_path(@booking), method: :delete, class: 'btn btn-primary' if current_user.guesthouse %>
    <%= button_to 'Cancelar Reserva', guest_cancel_booking_path(@booking), method: :delete, class: 'btn btn-primary' if current_user.guest? %>

  <% elsif @booking.in_progress? %>
    <h2>Estadia Ativa <%= @booking.code %></h2>
    <p><strong>Quarto: </strong><%= @booking.room.name %></p>
    <p><strong>Quantidade de hóspedes: </strong><%= @booking.guests_number %></p>
    <p><strong>Status: </strong><%= t(@booking.status) %></p>
    <p><strong>Check-in realizado em: </strong><%= l(@booking.check_in_done, format: '%d/%m/%Y, às %H:%M horas') %></p>
    <%= button_to 'Realizar Check-out', set_finished_booking_path(@booking), class: 'btn btn-primary' if current_user.guesthouse %>

  <% elsif @booking.finished? %>
    <h2>Hospedagem Finalizada <%= @booking.code %></h2>
    <% if current_user.guest? %>
      <p><strong>Pousada: </strong><%= @booking.guesthouse.brand_name %></p>
    <% end %>
    <p><strong>Quarto: </strong><%= @booking.room.name %></p>
    <p><strong>Quantidade de hóspedes: </strong><%= @booking.guests_number %></p>
    <p><strong>Status: </strong><%= t(@booking.status) %></p>
    <p><strong>Check-in realizado em: </strong><%= l(@booking.check_in_done, format: '%d/%m/%Y, às %H:%M horas') %></p>
    <p><strong>Check-out realizado em: </strong><%= l(@booking.check_out_done, format: '%d/%m/%Y, às %H:%M horas') %></p>
    <% if @booking.review.nil? && current_user.guest? %>
      <%= button_to 'Registrar Avaliação', new_booking_review_path(@booking), method: :get, class: 'btn btn-primary' %>
    <% else %>
      <h3>Avaliação da Hospedagem</h3>
      <p><strong>Nota: </strong><%= number_with_precision(@booking.review.score, separator: ',') %></p></p>
      <p><strong>Avaliação: </strong><%= @booking.review.review_text %></p>
      <% if @review.answer.nil? %>
        <%= button_to 'Responder Avaliação', answer_review_path(@review), method: :get, class: 'btn btn-primary' if current_user.guesthouse %>
      <% else %>
        <p><strong>Resposta: </strong><%= @booking.review.answer %></p>
      <% end %>
    <% end %>
  <% end %> 
</section>

app/views/bookings/show_availability.html.erb
<section>
  <h2><%= @room.name %> disponível entre os dias <%= l(@booking.check_in_date) %> - <%= l(@booking.check_out_date) %> </h2>
  <p><strong>Valor total das diárias: </strong><%= number_to_currency(@total_price, unit: "R$", separator: ",", delimiter: ".") %></p>
  <p>Para prosseguir com a reserva, você precisa criar sua conta ou fazer login: </p>
  <%= link_to 'Prosseguir com a Reserva', new_user_registration_path %>
</section>