config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'home#index'
  get 'my-guesthouse', to: 'guesthouses#my_guesthouse'
  get 'guesthouses_by_city/:city', to: 'guesthouses#by_city', as: 'guesthouses_by_city'

  resources :guesthouses, only: [:new, :create, :show, :edit, :update] do
    post :activate, on: :member
    post :inactivate, on: :member
    get 'search', on: :collection
    get 'bookings', on: :member
    get 'active_stays', on: :member
    get 'reviews', on: :member
    get 'all_reviews', on: :member
    resources :rooms, only: [:new, :create]
  end

  resources :rooms, only: [:show, :edit, :update] do
    post :set_available, on: :member
    post :set_unavailable, on: :member
    resources :custom_prices, only: [:index, :new, :create]
    resources :bookings, only: [:new, :create] do
      post 'check_availability', on: :collection
    end
  end

  resources :custom_prices, only: [:edit, :update]
  get 'confirm_booking', to: 'bookings#confirm_booking'
  get 'my-bookings', to: 'bookings#my_bookings'

  resources :bookings, only: [:show] do
    post :set_in_progress, on: :member
    post :set_finished, on: :member
    get 'payment', on: :member
    patch 'register_payment', on: :member
    delete 'host_cancel', on: :member
    delete 'guest_cancel', on: :member
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [] do
    get 'answer', on: :member
    patch 'register_answer', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :guesthouses, only: [:index, :show] do
        resources :rooms, only: [:index]
      end
      resources :rooms, only: [] do
        resources :bookings, only: [] do
          post 'check_availability', on: :collection
        end
      end
    end
  end

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger" role="alert">
  <p>Verifique os erros abaixo:</p>
    <ul>
      <% object.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <%= link_to 'Pousadaria', root_path, class: 'navbar-brand' %>
  <div class="collapse navbar-collapse">
    <div class="navbar-nav w-100 d-flex justify-content-end">
      <% if user_signed_in? %>            
        <% if current_user.guesthouse %>           
          <%= link_to 'Minha Pousada', my_guesthouse_path, class: 'nav-link' %>
          <%= link_to 'Reservas', bookings_guesthouse_path(current_user.guesthouse), class: 'nav-link' %>
          <%= link_to 'Estadias Ativas', active_stays_guesthouse_path(current_user.guesthouse), class: 'nav-link' %>
          <%= link_to 'Avaliações', reviews_guesthouse_path(current_user.guesthouse), class: 'nav-link' %>
        <% elsif current_user.guest? %>
          <%= link_to 'Minhas Reservas', my_bookings_path, class: 'nav-link' %>
        <% end %>
        <div class="d-flex align-items-center align-content-md-end">
          <%= current_user.name %>
          <%= button_to 'Sair', destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
          <% else %>
            <%= link_to 'Entrar na Conta', new_user_session_path, class: 'nav-link' %>
            <%= form_with(url: search_guesthouses_path, method: :get) do |f| %>
              <%= f.label :query, 'Buscar Pousada'%>
              <%= f.text_field :query %>
              <%= f.submit 'Buscar', class: 'btn btn-primary' %>
            <% end %>
          <% end %> 
        </div>  
    </div>
  </div> 
</nav>