config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'home#index'
  get 'my-guesthouse', to: 'guesthouses#my_guesthouse'
  get 'guesthouses_by_city/:city', to: 'guesthouses#by_city', as: 'guesthouses_by_city'

  resources :guesthouses, only: [:new, :create, :show, :edit, :update] do
    post :activate, on: :member
    post :inactivate, on: :member
    get 'search', on: :collection
    get 'bookings', on: :member
    get 'active_stays', on: :member
    get 'reviews', on: :member
    get 'all_reviews', on: :member
    resources :rooms, only: [:new, :create]
  end

  resources :rooms, only: [:show, :edit, :update] do
    post :set_available, on: :member
    post :set_unavailable, on: :member
    resources :custom_prices, only: [:index, :new, :create]
    resources :bookings, only: [:new, :create] do
      post 'check_availability', on: :collection
    end
  end

  resources :custom_prices, only: [:edit, :update]
  get 'confirm_booking', to: 'bookings#confirm_booking'
  get 'my-bookings', to: 'bookings#my_bookings'

  resources :bookings, only: [:show] do
    post :set_in_progress, on: :member
    post :set_finished, on: :member
    get 'payment', on: :member
    patch 'register_payment', on: :member
    delete 'host_cancel', on: :member
    delete 'guest_cancel', on: :member
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [] do
    get 'answer', on: :member
    patch 'register_answer', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :guesthouses, only: [:index, :show] do
        resources :rooms, only: [:index]
      end
      resources :rooms, only: [] do
        resources :bookings, only: [] do
          post 'check_availability', on: :collection
        end
      end
    end
  end

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :guesthouse
  has_many :custom_prices
  has_many :bookings
  has_many :users, through: :bookings
  enum status: {unavailable: 0, available: 2}

  validates :name, :description, :area, :max_guest, :default_price, presence: true

  def current_daily_price(date)
    default_price = self.default_price
    custom_prices = self.custom_prices
      
    custom_prices.each do |cp|
      if date >= cp.begin_date && date < cp.end_date
        return cp.price
      end
    end  
    default_price
  end

end

app/controllers/api/v1/rooms_controller.rb
class Api::V1::RoomsController < Api::V1::ApiController

  def index
    guesthouse = Guesthouse.find(params[:guesthouse_id])
    rooms = guesthouse.rooms.available
    render status: 200, json: rooms.as_json(only: [:id, :name, :description, :area, :max_guest, :default_price])
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :set_available, :set_unavailable]
  before_action :redirect_host_to_new
  before_action only: [:new, :create] do
    @guesthouse = Guesthouse.find(params[:guesthouse_id])
    check_user(@guesthouse)
  end
  before_action only: [:edit, :update, :set_available, :set_unavailable] do
    @room = Room.find(params[:id])
    check_user(@room.guesthouse)
  end
  before_action :room_unavailable, only: [:show]


  def new
    @room = @guesthouse.rooms.build
  end

  def create
    @room = @guesthouse.rooms.build(room_params)
    @room.guesthouse.user = current_user
    if @room.save
      redirect_to @room, notice: 'Quarto cadastrado com sucesso.'
    else
      flash.now[:notice] = 'Quarto não cadastrado.'
      render 'new'
    end
  end

  def show
    @custom_prices = @room.custom_prices
  end

  def edit; end

  def update
    if @room.update(room_params)
      redirect_to @room, notice: 'Quarto atualizado com sucesso.'
    else
      flash.now[:notice] = 'Quarto não atualizado.'
      render 'edit'
    end
  end

  def set_available
    @room.available!
    redirect_to room_path(@room.id), notice: 'Quarto disponibilizado com sucesso.'
  end

  def set_unavailable
    @room.unavailable!
    redirect_to room_path(@room.id), notice: 'Quarto indisponibilizado com sucesso.'
  end

  private

  def room_params
    params.require(:room).permit(:name, :description, :area, :max_guest, :default_price, :bathroom, :balcony, :air_conditioner, 
                                  :tv, :wardrobe, :safe, :accessible)
  end

end

app/views/rooms/_form.html.erb
<div>
  <%= render partial: 'shared/error_messages', locals: { object: @room } %>
</div>

<%= form_with(model: [@guesthouse, @room]) do |f| %>
<div class="field col-md-4">
  <%= f.label :name, class: "form-label" %>
  <%= f.text_field :name, class: "form-control" %>
</div>
<div class="field col-md-4">
  <%= f.label :description, class: "form-label" %>
  <%= f.text_area :description, class: "form-control" %>
</div>
<div class="field col-md-4">
  <%= f.label :area, class: "form-label" %>
  <%= f.number_field :area, class: "form-control" %>
</div>
<div class="field col-md-4">
  <%= f.label :max_guest, class: "form-label" %>
  <%= f.number_field :max_guest, class: "form-control" %>
</div>
<div class="field col-md-4">
  <%= f.label :default_price, class: "form-label" %>
  <%= f.number_field :default_price, class: "form-control" %>
</div>
<div class="form-check">
  <%= f.label :bathroom, class: "form-check-label" %>
  <%= f.check_box :bathroom, class: "form-check-input" %>
</div>
<div class="form-check">
  <%= f.label :balcony, class: "form-check-label" %>
  <%= f.check_box :balcony, class: "form-check-input" %>
</div>
<div class="form-check">
  <%= f.label :air_conditioner, class: "form-check-label" %>
  <%= f.check_box :air_conditioner, class: "form-check-input" %>
</div>
<div class="form-check">
  <%= f.label :tv, class: "form-check-label" %>
  <%= f.check_box :tv, class: "form-check-input" %>
</div>
<div class="form-check">
  <%= f.label :wardrobe, class: "form-check-label" %>
  <%= f.check_box :wardrobe, class: "form-check-input" %>
</div>
<div class="form-check">
  <%= f.label :safe, class: "form-check-label" %>
  <%= f.check_box :safe, class: "form-check-input" %>
</div>
<div class="form-check">
  <%= f.label :accessible, class: "form-check-label" %>
  <%= f.check_box :accessible, class: "form-check-input" %>
</div>
<br>
<div>
  <%= f.submit 'Salvar', class: "btn btn-primary" %>
</div>
<% end %>
<br>
<div>
  <%= link_to 'Voltar', my_guesthouse_path %>
</div>

app/views/rooms/edit.html.erb
<h2>Editar Quarto</h2>

<%= render 'form' %>

app/views/rooms/new.html.erb
<h2>Cadastrar Quarto</h2>

<%= render 'form' %>

app/views/rooms/show.html.erb
<section>
<% if current_user == @room.guesthouse.user %>
  <div>
    <p><strong>Status: </strong><%= I18n.t(@room.status) %></p>
    <% if @room.unavailable? %>
      <%= button_to 'Disponibilizar Quarto', set_available_room_path(@room), class: 'btn btn-primary' %>
    <% else %>
      <%= button_to 'Indisponibilizar Quarto', set_unavailable_room_path(@room), class: 'btn btn-primary' %>
    <% end %>
    <%= link_to 'Editar', edit_room_path(@room) %> |
    <%= link_to 'Cadastrar novo Preço Personalizado', new_room_custom_price_path(@room) %> |
    <%= link_to 'Voltar', guesthouse_path(@room.guesthouse) %>
  </div>
<% else %>
  <div>
    <%= link_to 'Voltar', guesthouse_path(@room.guesthouse) %>
  </div>
<% end %>
</section>

<section>
  <h2><%= @room.name %></h2>
  <p><strong>Descrição: </strong><%= @room.description %></p>
  <p><strong>Área (m²): </strong><%= @room.area %></p>
  <p><strong>Quantidade max. de hóspedes: </strong><%= @room.max_guest %></p>
  <p><strong>Valor da diária: </strong><%= number_to_currency(@room.current_daily_price(Date.today), unit: "R$", separator: ",", delimiter: ".") %></p>

  <p><strong>O que esse quarto oferece:</strong></p>
  <br>
  <% @room.attributes.each do |attribute, value| %>
    <% if value == true %>
      <ul>
        <li><%= Room.human_attribute_name(attribute) %></li>
      </ul>
    <% end %>
  <% end %>
  <% if current_user.nil? || current_user.guest?  %>
    <%= button_to 'Reservar', new_room_booking_path(@room.id), method: :get, class: 'btn btn-primary' %>
  <% end %>
</section>
<hr>
<section>
<% if current_user == @room.guesthouse.user  %>
  <div class="custom-prices">
    <h4><strong>Lista de Preços Personalizados:</strong></h4>
    <p><strong>Valor padrão da diária: </strong><%= number_to_currency(@room.default_price, unit: "R$", separator: ",", delimiter: ".") %></p>
    <% @custom_prices.each do |custom_price|%>
      <ul>
        <li><strong>Data de início: </strong><%= I18n.l(custom_price.begin_date, format: "%d/%m/%Y") %> | 
        <strong>Data de fim: </strong><%= I18n.l(custom_price.end_date, format: "%d/%m/%Y") %> | 
        <strong>Valor personalizado da diária: </strong><%= number_to_currency(custom_price.price, unit: "R$", separator: ",", delimiter: ".") %>
        <%= link_to 'Editar', edit_custom_price_path(custom_price) %></li>
      </ul>
    <% end %>
    
    <% if @custom_prices.empty? %>
      <p>Não existem preços personalizados cadastrados.</p>
    <% end %>
  </div>
<% end %>
</section>